version: '3'

services:
  frontend:
    build:
      context: ./LangGraph-GUI-frontend
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    network_mode: "host"

  backend:
    build:
      context: ./LangGraph-GUI-backend
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./LangGraph-GUI-backend/src/workspace:/app/src/workspace
    depends_on:
      - ollama
    network_mode: "host"

  ollama:
    build:
      context: ./ollama
    ports:
      - "127.0.0.1:11434:11434"
    network_mode: "host"
