services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend/src/:/app/src/
    network_mode: "host"

  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./backend/src/:/app/src/
    network_mode: "host"

  ollama:
    build:
      context: ./ollama
    ports:
      - "127.0.0.1:11434:11434"
    network_mode: "host"
