# backend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: langgraph-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: langgraph-gui-backend:latest  # Replace with your actual backend image name
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: OLLAMA_BASE_URL
            value: http://ollama-service.langgraph-gui:13666 # changed to service name
          - name: BACKEND_PORT
            value: "5000" # Wrap port in quotes to treat it as a string.